# fly.toml app configuration file generated for shopify-mock on 2023-06-10T20:06:27-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shopify-mock"
primary_region = "mia"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
